# Generated by Django 2.2 on 2020-10-02 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acknowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='otherSites_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('menu_name', models.CharField(max_length=200, unique=True)),
                ('other_nav', models.ForeignKey(blank=True, limit_choices_to={'id': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_menu', to='acknowledge.parent_menu')),
            ],
        ),
    ]
