# Generated by Django 3.1 on 2020-08-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200820_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayerstructure',
            name='lastname',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamplayerstructure',
            name='firstname',
            field=models.CharField(max_length=200),
        ),
    ]
