# Generated by Django 3.1 on 2020-08-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_teamplayerstructure_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamstructure',
            name='club_state',
        ),
    ]
