# Generated by Django 3.1 on 2020-08-20 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_teamstructure_club_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=200)),
                ('team2', models.CharField(max_length=200)),
                ('looser_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teammatchesloser', to='application.teamstructure')),
                ('winner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teammatcheswinner', to='application.teamstructure')),
            ],
        ),
        migrations.AlterField(
            model_name='teamplayerstructure',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='teamplayerstructure',
            name='firstname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='teamplayerstructure',
            name='identifier',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='teamplayerstructure',
            name='lastname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Tablepoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_point', models.IntegerField(blank=True, null=True)),
                ('matches', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='application.matches')),
            ],
        ),
        migrations.CreateModel(
            name='playerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.IntegerField(blank=True, null=True)),
                ('run', models.IntegerField(blank=True, null=True)),
                ('highest_scores', models.IntegerField(blank=True, null=True)),
                ('fifties', models.IntegerField(blank=True, null=True)),
                ('hundreds', models.IntegerField(blank=True, null=True)),
                ('team_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playerhistory', to='application.teamplayerstructure')),
            ],
        ),
    ]
