# Generated by Django 2.2 on 2020-10-02 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('borrower_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowers', to='user.UserDetail')),
                ('owes_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owes', to='user.UserDetail')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('borrower_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='user.UserDetail')),
                ('owes_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owes_by', to='user.UserDetail')),
            ],
        ),
    ]
