# Generated by Django 3.1.1 on 2020-10-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0002_auto_20201002_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ack_submenu',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'one '), (2, 'two')], default=2),
        ),
    ]
