# Generated by Django 3.1.1 on 2020-10-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0003_auto_20201004_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='ack_subpublicationmenu',
            name='file_type',
            field=models.SmallIntegerField(choices=[(1, 'pb'), (2, 'mat'), (3, 'sb1'), (4, 'sb2'), (5, 'misl')], default=5),
        ),
    ]
