# Generated by Django 3.1.1 on 2020-10-05 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0004_ack_subpublicationmenu_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ack_subnavy_orderssmenu',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'id': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ask_subnavy_ordersmenues', to='acknowledge.acknoledge_menu'),
        ),
    ]
