# Generated by Django 3.1.1 on 2020-10-05 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0008_ack_subnavy_instructionssmenu_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ack_navyinstructionname',
            name='folder_type',
        ),
        migrations.RemoveField(
            model_name='ack_navyinstructionname',
            name='menu_type',
        ),
    ]
