# Generated by Django 3.1.1 on 2020-10-09 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0017_auto_20201009_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acknowledge.ack_submenu'),
        ),
    ]
