from django.contrib import admin
from .models import (graphDetailUsed, ack_subMenuPolicyFile, ack_NavyInstructionname, ack_Navyname, ack_Standardsname, 
	ack_guidelinesname, BRsmenu, ack_subpublicationmenu,acknoledge_menu,parent_menu,ack_submenu,ack_policyname, 
	ack_policypolicyfile,ack_publicationname, ack_subGuidelinesmenu, ack_subStandardsmenu, ack_subNavy_Orderssmenu, graphDetail, 
	 ack_subNavy_Instructionssmenu, KnowledgeUser, PublicationUser, InstructionUser, NavyUser, StandardUser, GuideLinesUser)
admin.site.register(acknoledge_menu)
admin.site.register(parent_menu)
admin.site.register(ack_submenu)
admin.site.register(ack_policyname)
#admin.site.register(ack_policypolicyfile)
#admin.site.register(ack_publicationfile)
admin.site.register(ack_subGuidelinesmenu)
admin.site.register(ack_publicationname)
admin.site.register(ack_subpublicationmenu)
admin.site.register(ack_subStandardsmenu)
admin.site.register(ack_subNavy_Orderssmenu)
admin.site.register(ack_subNavy_Instructionssmenu)
#admin.site.register(ack_subNHQe_Librarylinesmenu)
#admin.site.register(BRsmenu)
admin.site.register(ack_guidelinesname)
admin.site.register(ack_Standardsname)
admin.site.register(ack_Navyname)
admin.site.register(ack_NavyInstructionname)
admin.site.register(graphDetail)
admin.site.register(ack_subMenuPolicyFile)
admin.site.register(graphDetailUsed)
admin.site.register(KnowledgeUser)
admin.site.register(PublicationUser)
admin.site.register(GuideLinesUser)
admin.site.register(StandardUser)
admin.site.register(NavyUser)
admin.site.register(InstructionUser)
